### ISSUE TITLE
How to use MongoDB instead of MongoClient()

### ISSUE THREAD

**Issue by basantk** [LeWestopher/cakephp-monga#8]
$cake_monga = ConnectionManager::get('datasource');

I want to log query in file like mysql.

and how can i use MongoDB conenction? instead of MongoClient() because MongoClient is deprecated.

**Comment by basantk** [comment]
How to use MongoDB instead of MongoClient()
please suggest ?

**Comment by LeWestopher** [comment]
This plugin currently doesn't support the new MongoDB extension with PHP, only the old Mongo client.  It is in the pipes for v2.0 of this plugin to drop the usage of Monga and use the MongoDB extension solely.
